export type Quadrant =
  | "high-energy-pleasant"
  | "high-energy-unpleasant"
  | "low-energy-pleasant"
  | "low-energy-unpleasant";

export interface Emotion {
  name: string;
  quadrant: Quadrant;
  emoji: string;
}

export const QUADRANT_INFO: Record<
  Quadrant,
  { label: string; color: string; bg: string; icon: string; description: string }
> = {
  "high-energy-pleasant": {
    label: "High Energy + Pleasant",
    color: "text-amber-600",
    bg: "bg-amber-50 border-amber-300",
    icon: "⚡😊",
    description: "Feeling alive and loving it",
  },
  "high-energy-unpleasant": {
    label: "High Energy + Unpleasant",
    color: "text-red-600",
    bg: "bg-red-50 border-red-300",
    icon: "⚡😤",
    description: "Wound up and not great",
  },
  "low-energy-pleasant": {
    label: "Low Energy + Pleasant",
    color: "text-emerald-600",
    bg: "bg-emerald-50 border-emerald-300",
    icon: "🍃😌",
    description: "Chill and content",
  },
  "low-energy-unpleasant": {
    label: "Low Energy + Unpleasant",
    color: "text-indigo-600",
    bg: "bg-indigo-50 border-indigo-300",
    icon: "🍃😔",
    description: "Running low",
  },
};

export const EMOTIONS: Emotion[] = [
  // === HIGH ENERGY + PLEASANT (38 emotions) ===
  { name: "Excited", quadrant: "high-energy-pleasant", emoji: "🤩" },
  { name: "Joyful", quadrant: "high-energy-pleasant", emoji: "😄" },
  { name: "Thrilled", quadrant: "high-energy-pleasant", emoji: "🎉" },
  { name: "Ecstatic", quadrant: "high-energy-pleasant", emoji: "🥳" },
  { name: "Elated", quadrant: "high-energy-pleasant", emoji: "😁" },
  { name: "Enthusiastic", quadrant: "high-energy-pleasant", emoji: "🔥" },
  { name: "Energized", quadrant: "high-energy-pleasant", emoji: "⚡" },
  { name: "Inspired", quadrant: "high-energy-pleasant", emoji: "✨" },
  { name: "Motivated", quadrant: "high-energy-pleasant", emoji: "💪" },
  { name: "Passionate", quadrant: "high-energy-pleasant", emoji: "❤️‍🔥" },
  { name: "Playful", quadrant: "high-energy-pleasant", emoji: "😜" },
  { name: "Amused", quadrant: "high-energy-pleasant", emoji: "😂" },
  { name: "Cheerful", quadrant: "high-energy-pleasant", emoji: "😊" },
  { name: "Delighted", quadrant: "high-energy-pleasant", emoji: "🥰" },
  { name: "Euphoric", quadrant: "high-energy-pleasant", emoji: "🤯" },
  { name: "Giddy", quadrant: "high-energy-pleasant", emoji: "🤭" },
  { name: "Grateful", quadrant: "high-energy-pleasant", emoji: "🙏" },
  { name: "Hopeful", quadrant: "high-energy-pleasant", emoji: "🌟" },
  { name: "Optimistic", quadrant: "high-energy-pleasant", emoji: "😎" },
  { name: "Proud", quadrant: "high-energy-pleasant", emoji: "🏆" },
  { name: "Amazed", quadrant: "high-energy-pleasant", emoji: "😲" },
  { name: "Confident", quadrant: "high-energy-pleasant", emoji: "😤" },
  { name: "Creative", quadrant: "high-energy-pleasant", emoji: "🎨" },
  { name: "Curious", quadrant: "high-energy-pleasant", emoji: "🧐" },
  { name: "Daring", quadrant: "high-energy-pleasant", emoji: "🦁" },
  { name: "Determined", quadrant: "high-energy-pleasant", emoji: "🎯" },
  { name: "Empowered", quadrant: "high-energy-pleasant", emoji: "👑" },
  { name: "Exhilarated", quadrant: "high-energy-pleasant", emoji: "🎢" },
  { name: "Festive", quadrant: "high-energy-pleasant", emoji: "🎊" },
  { name: "Free", quadrant: "high-energy-pleasant", emoji: "🕊️" },
  { name: "Victorious", quadrant: "high-energy-pleasant", emoji: "✌️" },
  { name: "Loved", quadrant: "high-energy-pleasant", emoji: "💕" },
  { name: "Adventurous", quadrant: "high-energy-pleasant", emoji: "🗺️" },
  { name: "Alive", quadrant: "high-energy-pleasant", emoji: "🌈" },
  { name: "Blissful", quadrant: "high-energy-pleasant", emoji: "😇" },
  { name: "Courageous", quadrant: "high-energy-pleasant", emoji: "🦸" },
  { name: "Pumped", quadrant: "high-energy-pleasant", emoji: "🏋️" },
  { name: "Radiant", quadrant: "high-energy-pleasant", emoji: "☀️" },

  // === HIGH ENERGY + UNPLEASANT (37 emotions) ===
  { name: "Anxious", quadrant: "high-energy-unpleasant", emoji: "😰" },
  { name: "Stressed", quadrant: "high-energy-unpleasant", emoji: "😫" },
  { name: "Angry", quadrant: "high-energy-unpleasant", emoji: "😡" },
  { name: "Frustrated", quadrant: "high-energy-unpleasant", emoji: "😤" },
  { name: "Overwhelmed", quadrant: "high-energy-unpleasant", emoji: "🤯" },
  { name: "Panicked", quadrant: "high-energy-unpleasant", emoji: "😱" },
  { name: "Irritated", quadrant: "high-energy-unpleasant", emoji: "😒" },
  { name: "Agitated", quadrant: "high-energy-unpleasant", emoji: "😠" },
  { name: "Nervous", quadrant: "high-energy-unpleasant", emoji: "😬" },
  { name: "Restless", quadrant: "high-energy-unpleasant", emoji: "🫠" },
  { name: "Tense", quadrant: "high-energy-unpleasant", emoji: "😣" },
  { name: "Worried", quadrant: "high-energy-unpleasant", emoji: "😟" },
  { name: "Furious", quadrant: "high-energy-unpleasant", emoji: "🤬" },
  { name: "Jealous", quadrant: "high-energy-unpleasant", emoji: "💚" },
  { name: "Envious", quadrant: "high-energy-unpleasant", emoji: "👀" },
  { name: "Impatient", quadrant: "high-energy-unpleasant", emoji: "⏰" },
  { name: "Defensive", quadrant: "high-energy-unpleasant", emoji: "🛡️" },
  { name: "Embarrassed", quadrant: "high-energy-unpleasant", emoji: "🫣" },
  { name: "Flustered", quadrant: "high-energy-unpleasant", emoji: "🥴" },
  { name: "Horrified", quadrant: "high-energy-unpleasant", emoji: "😨" },
  { name: "Hostile", quadrant: "high-energy-unpleasant", emoji: "👊" },
  { name: "Hysterical", quadrant: "high-energy-unpleasant", emoji: "😵" },
  { name: "Manic", quadrant: "high-energy-unpleasant", emoji: "🌀" },
  { name: "Outraged", quadrant: "high-energy-unpleasant", emoji: "💢" },
  { name: "Pressured", quadrant: "high-energy-unpleasant", emoji: "🏃" },
  { name: "Rattled", quadrant: "high-energy-unpleasant", emoji: "😵‍💫" },
  { name: "Resentful", quadrant: "high-energy-unpleasant", emoji: "😑" },
  { name: "Shocked", quadrant: "high-energy-unpleasant", emoji: "⚡" },
  { name: "Suspicious", quadrant: "high-energy-unpleasant", emoji: "🤨" },
  { name: "Trapped", quadrant: "high-energy-unpleasant", emoji: "🔒" },
  { name: "Frantic", quadrant: "high-energy-unpleasant", emoji: "🏃‍♂️" },
  { name: "Guilty", quadrant: "high-energy-unpleasant", emoji: "😞" },
  { name: "Conflicted", quadrant: "high-energy-unpleasant", emoji: "⚖️" },
  { name: "Exasperated", quadrant: "high-energy-unpleasant", emoji: "🤦" },
  { name: "Apprehensive", quadrant: "high-energy-unpleasant", emoji: "😧" },
  { name: "Insecure", quadrant: "high-energy-unpleasant", emoji: "🥺" },
  { name: "Scattered", quadrant: "high-energy-unpleasant", emoji: "🧩" },

  // === LOW ENERGY + PLEASANT (38 emotions) ===
  { name: "Calm", quadrant: "low-energy-pleasant", emoji: "😌" },
  { name: "Content", quadrant: "low-energy-pleasant", emoji: "🙂" },
  { name: "Peaceful", quadrant: "low-energy-pleasant", emoji: "☮️" },
  { name: "Relaxed", quadrant: "low-energy-pleasant", emoji: "😎" },
  { name: "Serene", quadrant: "low-energy-pleasant", emoji: "🧘" },
  { name: "Cozy", quadrant: "low-energy-pleasant", emoji: "🛋️" },
  { name: "Comfortable", quadrant: "low-energy-pleasant", emoji: "😊" },
  { name: "Satisfied", quadrant: "low-energy-pleasant", emoji: "😋" },
  { name: "Thankful", quadrant: "low-energy-pleasant", emoji: "💝" },
  { name: "Mellow", quadrant: "low-energy-pleasant", emoji: "🎵" },
  { name: "Tender", quadrant: "low-energy-pleasant", emoji: "🤗" },
  { name: "Warm", quadrant: "low-energy-pleasant", emoji: "🌞" },
  { name: "Secure", quadrant: "low-energy-pleasant", emoji: "🏡" },
  { name: "Thoughtful", quadrant: "low-energy-pleasant", emoji: "🤔" },
  { name: "Gentle", quadrant: "low-energy-pleasant", emoji: "🌸" },
  { name: "Sentimental", quadrant: "low-energy-pleasant", emoji: "🥹" },
  { name: "Nostalgic", quadrant: "low-energy-pleasant", emoji: "📷" },
  { name: "Relieved", quadrant: "low-energy-pleasant", emoji: "😮‍💨" },
  { name: "Fulfilled", quadrant: "low-energy-pleasant", emoji: "✅" },
  { name: "Grounded", quadrant: "low-energy-pleasant", emoji: "🌳" },
  { name: "Balanced", quadrant: "low-energy-pleasant", emoji: "⚖️" },
  { name: "At ease", quadrant: "low-energy-pleasant", emoji: "🍵" },
  { name: "Blessed", quadrant: "low-energy-pleasant", emoji: "🙌" },
  { name: "Carefree", quadrant: "low-energy-pleasant", emoji: "🎈" },
  { name: "Compassionate", quadrant: "low-energy-pleasant", emoji: "💗" },
  { name: "Dreamy", quadrant: "low-energy-pleasant", emoji: "💭" },
  { name: "Graceful", quadrant: "low-energy-pleasant", emoji: "🦢" },
  { name: "Harmonious", quadrant: "low-energy-pleasant", emoji: "🎶" },
  { name: "Laid-back", quadrant: "low-energy-pleasant", emoji: "🏖️" },
  { name: "Meditative", quadrant: "low-energy-pleasant", emoji: "🧘‍♀️" },
  { name: "Nurturing", quadrant: "low-energy-pleasant", emoji: "🌱" },
  { name: "Patient", quadrant: "low-energy-pleasant", emoji: "⏳" },
  { name: "Refreshed", quadrant: "low-energy-pleasant", emoji: "💧" },
  { name: "Restful", quadrant: "low-energy-pleasant", emoji: "😴" },
  { name: "Safe", quadrant: "low-energy-pleasant", emoji: "🛡️" },
  { name: "Snug", quadrant: "low-energy-pleasant", emoji: "🧸" },
  { name: "Tranquil", quadrant: "low-energy-pleasant", emoji: "🌊" },
  { name: "Zen", quadrant: "low-energy-pleasant", emoji: "☯️" },

  // === LOW ENERGY + UNPLEASANT (37 emotions) ===
  { name: "Sad", quadrant: "low-energy-unpleasant", emoji: "😢" },
  { name: "Tired", quadrant: "low-energy-unpleasant", emoji: "😴" },
  { name: "Exhausted", quadrant: "low-energy-unpleasant", emoji: "🥱" },
  { name: "Lonely", quadrant: "low-energy-unpleasant", emoji: "😔" },
  { name: "Bored", quadrant: "low-energy-unpleasant", emoji: "😐" },
  { name: "Melancholy", quadrant: "low-energy-unpleasant", emoji: "🌧️" },
  { name: "Drained", quadrant: "low-energy-unpleasant", emoji: "🪫" },
  { name: "Homesick", quadrant: "low-energy-unpleasant", emoji: "🏠" },
  { name: "Disconnected", quadrant: "low-energy-unpleasant", emoji: "📵" },
  { name: "Apathetic", quadrant: "low-energy-unpleasant", emoji: "😶" },
  { name: "Numb", quadrant: "low-energy-unpleasant", emoji: "🫥" },
  { name: "Defeated", quadrant: "low-energy-unpleasant", emoji: "🏳️" },
  { name: "Hopeless", quadrant: "low-energy-unpleasant", emoji: "😞" },
  { name: "Gloomy", quadrant: "low-energy-unpleasant", emoji: "☁️" },
  { name: "Burnt out", quadrant: "low-energy-unpleasant", emoji: "🔥" },
  { name: "Sluggish", quadrant: "low-energy-unpleasant", emoji: "🐌" },
  { name: "Lost", quadrant: "low-energy-unpleasant", emoji: "🧭" },
  { name: "Empty", quadrant: "low-energy-unpleasant", emoji: "🕳️" },
  { name: "Withdrawn", quadrant: "low-energy-unpleasant", emoji: "🐚" },
  { name: "Helpless", quadrant: "low-energy-unpleasant", emoji: "🆘" },
  { name: "Disappointed", quadrant: "low-energy-unpleasant", emoji: "😕" },
  { name: "Discouraged", quadrant: "low-energy-unpleasant", emoji: "👎" },
  { name: "Despondent", quadrant: "low-energy-unpleasant", emoji: "💔" },
  { name: "Distracted", quadrant: "low-energy-unpleasant", emoji: "🫤" },
  { name: "Down", quadrant: "low-energy-unpleasant", emoji: "⬇️" },
  { name: "Flat", quadrant: "low-energy-unpleasant", emoji: "➖" },
  { name: "Fragile", quadrant: "low-energy-unpleasant", emoji: "🥀" },
  { name: "Heavy", quadrant: "low-energy-unpleasant", emoji: "🪨" },
  { name: "Indifferent", quadrant: "low-energy-unpleasant", emoji: "🤷" },
  { name: "Invisible", quadrant: "low-energy-unpleasant", emoji: "👻" },
  { name: "Listless", quadrant: "low-energy-unpleasant", emoji: "😑" },
  { name: "Neglected", quadrant: "low-energy-unpleasant", emoji: "🥀" },
  { name: "Pessimistic", quadrant: "low-energy-unpleasant", emoji: "🌑" },
  { name: "Regretful", quadrant: "low-energy-unpleasant", emoji: "😿" },
  { name: "Stuck", quadrant: "low-energy-unpleasant", emoji: "🪤" },
  { name: "Vulnerable", quadrant: "low-energy-unpleasant", emoji: "🫧" },
  { name: "Weary", quadrant: "low-energy-unpleasant", emoji: "😩" },
];

export function getEmotionsByQuadrant(quadrant: Quadrant): Emotion[] {
  return EMOTIONS.filter((e) => e.quadrant === quadrant);
}

export function getEmotionByName(name: string): Emotion | undefined {
  return EMOTIONS.find((e) => e.name === name);
}
